name: Deploy a Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v4

      - name: Deploy via FTP a Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: 195.179.236.12
          username: u449988667.leystudiohn.com
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          timeout: 120000
          local-dir: ./
          server-dir: /public_html/
          exclude: |
            **/.*
            **/.git/**
            **/.github/**
            **/.DS_Store
            **/node_modules/**
            Ley's Studio - Precios.pdf
            LeyStudio_Dashboard.html
            Logo Moda Femenina Minimalista Negro y Rosa - 10 - Editado.PNG
            LogoPrincipal.png
            leystudio_demo_data.json
